api_platform:
    resource: .
    type: api_platform
    prefix: /api
app:
    path: /
    controller: App\Controller\PublicController
app1:
    path: /{slug}
    controller: App\Controller\PublicController
app2:
    path: /{slug}/{id}
    controller: App\Controller\PublicController